name: Deploy Demo App

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
  
    - name: Build with Maven
      run: mvn clean package
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to IBM Cloud Container Registry
      run: echo "${{ secrets.IBM_CLOUD_API_KEY }}" | docker login -u iamapikey --password-stdin icr.io

    - name: Build and push Docker image
      run: |
        docker build -t icr.io/talento-digital/demoapp:latest .
        docker push icr.io/talento-digital/demoapp:latest